"""Expose Pydantic schemas for convenient imports."""

from .account import (
    ClientAccountCreate,
    ClientAccountListResponse,
    ClientAccountPaymentCreate,
    ClientAccountPaymentListResponse,
    ClientAccountPaymentRead,
    ClientAccountRead,
    ClientAccountUpdate,
    PrincipalAccountCreate,
    PrincipalAccountListResponse,
    PrincipalAccountRead,
    PrincipalAccountUpdate,
)
from .common import PaginatedResponse
from .client import (
    ClientBase,
    ClientCreate,
    ClientImportError,
    ClientImportRequest,
    ClientImportTemplateRequest,
    ClientImportRowSummary,
    ClientImportSummary,
    ClientListResponse,
    ClientRead,
    ClientUpdate,
    ZoneSummary,
)
from .expense import ExpenseBase, ExpenseCreate, ExpenseListResponse, ExpenseRead
from .inventory import (
    InventoryBase,
    InventoryCreate,
    InventoryListResponse,
    InventoryRead,
    InventoryUpdate,
)
from .ip_pool import (
    BaseIpPoolBase,
    BaseIpPoolCreate,
    BaseIpPoolListResponse,
    BaseIpPoolRead,
    BaseIpPoolUpdate,
    BaseIpReservationBase,
    BaseIpReservationCreate,
    BaseIpReservationListResponse,
    BaseIpReservationRead,
    BaseIpReservationUpdate,
    IpAssignmentConsistencyReport,
    IpAssignmentInconsistency,
    IpAssignmentHistoryClient,
    IpAssignmentHistoryListResponse,
    IpAssignmentHistoryRead,
    IpHygieneRunResult,
    IpPoolSummaryItem,
    IpPoolSummaryResponse,
    IpUsageBreakdown,
    IpUsageReport,
)
from .metrics import (
    BaseCostUpdateRequest,
    BaseCostUpdateResponse,
    CommunityMetrics,
    DashboardClient,
    DashboardMetricsResponse,
    DashboardMetricsSummary,
    MetricsOverview,
    MetricsResponse,
    SchedulerHealthResponse,
    SchedulerJobHealth,
    StatusFilter,
)
from .integrity import (
    CounterMismatch,
    PaymentClientMismatch,
    PaymentConsistencyReport,
)
from .payment import (
    OverduePeriod,
    OverduePeriodListResponse,
    PaymentDuplicateCheck,
    PaymentBalanceState,
    PaymentPreviewResult,
    PaymentBalanceSnapshot,
    PaymentCaptureSummary,
    PaymentMethodBreakdown,
    PaymentReceipt,
    PaymentSuggestedAmount,
    PaymentScheduleCreate,
    PaymentScheduleListResponse,
    PaymentScheduleRead,
    PeriodPaymentStatus,
    ServicePaymentBase,
    ServicePaymentCreate,
    ServicePaymentListResponse,
    ServicePaymentRead,
    ServicePaymentResult,
    ServicePaymentWithSummary,
    ServicePaymentUpdate,
    ServicePeriodStatus,
    ServicePeriodStatusListResponse,
)
from .pos import (
    PosProductCreate,
    PosProductListResponse,
    PosProductRead,
    PosProductUpdate,
    PosSaleCreate,
    PosSaleListResponse,
    PosSaleRead,
)
from .reseller import (
    ResellerBase,
    ResellerCreate,
    ResellerDeliveryCreate,
    ResellerDeliveryItemBase,
    ResellerDeliveryRead,
    ResellerRead,
    ResellerSettlementCreate,
    ResellerSettlementRead,
)
from .service_plan import (
    ServicePlanBase,
    ServicePlanCreate,
    ServicePlanListResponse,
    ServicePlanRead,
    ServicePlanUpdate,
)
from .service import (
    ClientContractsResponse,
    ClientServiceBase,
    ClientServiceBulkCreate,
    ClientServiceCreate,
    ClientServiceInlineCreate,
    ClientServiceListResponse,
    ClientServiceRead,
    ClientServiceUpdate,
    ContractedServiceSummary,
    ProrationPreview,
    ServiceBalance,
    ServiceDebtRead,
    ServiceDebtUpdate,
)
from .auth import AdminLoginRequest, TokenResponse

__all__ = [
    "PrincipalAccountCreate",
    "PrincipalAccountRead",
    "PrincipalAccountUpdate",
    "PrincipalAccountListResponse",
    "ClientAccountCreate",
    "ClientAccountRead",
    "ClientAccountUpdate",
    "ClientAccountListResponse",
    "ClientAccountPaymentCreate",
    "ClientAccountPaymentRead",
    "ClientAccountPaymentListResponse",
    "ClientBase",
    "ClientCreate",
    "ClientRead",
    "ClientListResponse",
    "ClientUpdate",
    "ClientImportError",
    "ClientImportRequest",
    "ClientImportTemplateRequest",
    "ClientImportSummary",
    "ClientImportRowSummary",
    "ZoneSummary",
    "ClientServiceBase",
    "ClientServiceBulkCreate",
    "ClientServiceCreate",
    "ClientServiceInlineCreate",
    "ClientServiceRead",
    "ClientServiceUpdate",
    "ClientServiceListResponse",
    "ClientContractsResponse",
    "ContractedServiceSummary",
    "ProrationPreview",
    "ServiceBalance",
    "ServiceDebtRead",
    "ServiceDebtUpdate",
    "PaginatedResponse",
    "ServicePaymentBase",
    "ServicePaymentCreate",
    "PaymentBalanceState",
    "PaymentBalanceSnapshot",
    "PaymentCaptureSummary",
    "PaymentPreviewResult",
    "PaymentMethodBreakdown",
    "ServicePaymentRead",
    "ServicePaymentListResponse",
    "ServicePaymentResult",
    "ServicePaymentWithSummary",
    "ServicePaymentUpdate",
    "ServicePeriodStatus",
    "ServicePeriodStatusListResponse",
    "PeriodPaymentStatus",
    "OverduePeriod",
    "OverduePeriodListResponse",
    "PaymentDuplicateCheck",
    "PaymentSuggestedAmount",
    "PaymentScheduleCreate",
    "PaymentScheduleRead",
    "PaymentScheduleListResponse",
    "PaymentReceipt",
    "PosProductCreate",
    "PosProductRead",
    "PosProductUpdate",
    "PosProductListResponse",
    "PosSaleCreate",
    "PosSaleRead",
    "PosSaleListResponse",
    "ExpenseBase",
    "ExpenseCreate",
    "ExpenseRead",
    "ExpenseListResponse",
    "InventoryBase",
    "InventoryCreate",
    "InventoryRead",
    "InventoryUpdate",
    "InventoryListResponse",
    "BaseIpPoolBase",
    "BaseIpPoolCreate",
    "BaseIpPoolRead",
    "BaseIpPoolUpdate",
    "BaseIpPoolListResponse",
    "BaseIpReservationBase",
    "BaseIpReservationCreate",
    "BaseIpReservationRead",
    "BaseIpReservationUpdate",
    "BaseIpReservationListResponse",
    "IpAssignmentConsistencyReport",
    "IpAssignmentInconsistency",
    "IpAssignmentHistoryClient",
    "IpAssignmentHistoryRead",
    "IpAssignmentHistoryListResponse",
    "IpPoolSummaryItem",
    "IpPoolSummaryResponse",
    "ResellerBase",
    "ResellerCreate",
    "ResellerDeliveryCreate",
    "ResellerDeliveryItemBase",
    "ResellerDeliveryRead",
    "ResellerRead",
    "ResellerSettlementCreate",
    "ResellerSettlementRead",
    "MetricsOverview",
    "CommunityMetrics",
    "MetricsResponse",
    "SchedulerJobHealth",
    "SchedulerHealthResponse",
    "StatusFilter",
    "CounterMismatch",
    "PaymentClientMismatch",
    "PaymentConsistencyReport",
    "DashboardClient",
    "DashboardMetricsSummary",
    "DashboardMetricsResponse",
    "BaseCostUpdateRequest",
    "BaseCostUpdateResponse",
    "AdminLoginRequest",
    "TokenResponse",
    "ServicePlanBase",
    "ServicePlanSummary",
    "ServicePlanCreate",
    "ServicePlanUpdate",
    "ServicePlanRead",
    "ServicePlanListResponse",
]
from .service import (
    ClientServiceBase,
    ClientServiceBulkCreate,
    ClientServiceCreate,
    ClientServiceInlineCreate,
    ClientServiceListResponse,
    ClientServiceRead,
    ClientServiceUpdate,
    ServiceDebtRead,
    ServiceDebtUpdate,
    ServicePlanSummary,
)

# Resolve forward references for schemas that rely on cross-module types.
ServicePaymentRead.model_rebuild(
    _types_namespace={
        "ClientRead": ClientRead,
        "ClientServiceRead": ClientServiceRead,
    }
)
ClientListResponse.model_rebuild(_types_namespace={"ClientRead": ClientRead})
ClientServiceListResponse.model_rebuild(
    _types_namespace={"ClientServiceRead": ClientServiceRead}
)
ServicePaymentListResponse.model_rebuild(
    _types_namespace={"ServicePaymentRead": ServicePaymentRead}
)
ServicePaymentWithSummary.model_rebuild(
    _types_namespace={
        "ClientRead": ClientRead,
        "ClientServiceRead": ClientServiceRead,
        "PaymentCaptureSummary": PaymentCaptureSummary,
        "PaymentBalanceSnapshot": PaymentBalanceSnapshot,
    }
)
PaymentPreviewResult.model_rebuild(
    _types_namespace={
        "PaymentCaptureSummary": PaymentCaptureSummary,
        "PaymentBalanceSnapshot": PaymentBalanceSnapshot,
    }
)
PaymentScheduleRead.model_rebuild(
    _types_namespace={
        "ClientRead": ClientRead,
        "ClientServiceRead": ClientServiceRead,
    }
)
PaymentScheduleListResponse.model_rebuild(
    _types_namespace={"PaymentScheduleRead": PaymentScheduleRead}
)
